# -*- coding: utf-8 -*-
"""3ATICS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s2WRa6QGy_xRqY2JBp6f5x0SzpMAqK2Z
"""

!pip install -q --upgrade pip
!pip install -q \
  pandas numpy tqdm rapidfuzz scikit-learn networkx datasets \
  transformers==4.44.2 accelerate==0.33.0 bitsandbytes==0.45.5 \
  torch regex tabulate

from datasets import load_dataset
import pandas as pd
import numpy as np
import random
from pathlib import Path
from collections import Counter, defaultdict
from tqdm.auto import tqdm
import json
import re
import os
import itertools
from rapidfuzz import fuzz

SEED = 42
random.seed(SEED)
np.random.seed(SEED)

DATASET_ID = "willcb/wdc-products-multi"

MODEL_ID = "Qwen/Qwen2.5-7B-Instruct"

MAX_ATTRS_PER_SOURCE_FOR_LLM = 35
MAX_LLM_LINKAGE_CALLS = 300
MAX_LLM_FUSION_CALLS = 50

MATCH_THRESHOLD = 0.40
BORDERLINE_LOW = 0.35
BORDERLINE_HIGH = 0.50

PROJECT_DIR = Path("/content/llm_bdi_project")
DATA_DIR = PROJECT_DIR / "data"
RAW_DIR = DATA_DIR / "raw"
PROCESSED_DIR = DATA_DIR / "processed"
RESULTS_DIR = PROJECT_DIR / "results"
PROMPTS_DIR = PROJECT_DIR / "prompts"

for d in [PROJECT_DIR, DATA_DIR, RAW_DIR, PROCESSED_DIR, RESULTS_DIR, PROMPTS_DIR]:
    d.mkdir(parents=True, exist_ok=True)

DATASET_ID = "willcb/wdc-products-multi"

print("Loading dataset:", DATASET_ID)
ds = load_dataset(DATASET_ID, split="train")
df_raw = ds.to_pandas()

print("Raw shape:", df_raw.shape)
print(df_raw.columns)
df_raw.head()

required_cols = ["id", "brand", "title", "description", "price", "priceCurrency", "cluster_id"]
missing = [c for c in required_cols if c not in df_raw.columns]
if missing:
    raise ValueError(f"Missing expected columns: {missing}")

df = df_raw[required_cols].copy()

df["cluster_id"] = df["cluster_id"].astype(str)
df["id"] = df["id"].astype(str)

df = df.dropna(subset=["title", "cluster_id"])
df["title"] = df["title"].astype(str)

cluster_sizes = df.groupby("cluster_id").size()
eligible_clusters = cluster_sizes[cluster_sizes >= 2].sort_values(ascending=False).index.tolist()

print("Eligible clusters >=2 records:", len(eligible_clusters))

selected_clusters = []
n_records = 0

for cid in eligible_clusters:
    selected_clusters.append(cid)
    n_records += min(cluster_sizes[cid], 6)
    if n_records >= 1800 and len(selected_clusters) >= 300:
        break

df = df[df["cluster_id"].isin(selected_clusters)].copy()

df = (
    df.sort_values(["cluster_id", "id"])
      .groupby("cluster_id")
      .head(6)
      .reset_index(drop=True)
)

print("Working records:", len(df))
print("Working entities:", df["cluster_id"].nunique())

SOURCE_NAMES = ["source_alpha", "source_beta", "source_gamma"]

df["within_cluster_idx"] = df.groupby("cluster_id").cumcount()
df["source"] = df["within_cluster_idx"].apply(lambda x: SOURCE_NAMES[x % 3])

df["record_id"] = [f"r{i}" for i in range(len(df))]
df["spec_id"] = df["source"] + "//" + df["id"].astype(str)
df["entity_id"] = df["cluster_id"].astype(str)

print(df[["record_id", "spec_id", "source", "entity_id", "title"]].head())

MEDIATED_SCHEMA = [
    "title",
    "brand",
    "description",
    "price",
    "priceCurrency"
]

SOURCE_SCHEMAS = {
    "source_alpha": {
        "title": "product_name",
        "brand": "manufacturer",
        "description": "details",
        "price": "cost",
        "priceCurrency": "currency"
    },
    "source_beta": {
        "title": "name",
        "brand": "brand_name",
        "description": "description_text",
        "price": "amount",
        "priceCurrency": "currency_code"
    },
    "source_gamma": {
        "title": "item_title",
        "brand": "maker",
        "description": "specifications",
        "price": "listed_price",
        "priceCurrency": "money"
    }
}

def safe_value(x):
    if pd.isna(x):
        return ""
    return str(x).strip()

def row_to_attrs(row):
    source = row["source"]
    mapping = SOURCE_SCHEMAS[source]
    attrs = {}

    for mediated_attr, source_attr in mapping.items():
        value = safe_value(row[mediated_attr])
        if value:
            attrs[source_attr] = value

    return attrs

records = []
for _, row in df.iterrows():
    records.append({
        "record_id": row["record_id"],
        "spec_id": row["spec_id"],
        "source": row["source"],
        "entity_id": row["entity_id"],
        "attrs": row_to_attrs(row)
    })

work_records = pd.DataFrame(records)

print("work_records:", work_records.shape)
print("sources:", work_records["source"].nunique())
print("entities:", work_records["entity_id"].nunique())

schema_rows = []
for source, mapping in SOURCE_SCHEMAS.items():
    for mediated_attr, source_attr in mapping.items():
        schema_rows.append({
            "source": source,
            "attribute": source_attr,
            "source_attribute_id": f"{source}//{source_attr}",
            "target_attribute_name": mediated_attr
        })

schema_gt = pd.DataFrame(schema_rows)

def build_attribute_profile(records_df):
    rows = []
    for _, row in records_df.iterrows():
        source = row["source"]
        attrs = row["attrs"]
        for k, v in attrs.items():
            source_attribute_id = f"{source}//{k}"
            rows.append({
                "source": source,
                "attribute": k,
                "source_attribute_id": source_attribute_id,
                "value": str(v)
            })
    return pd.DataFrame(rows)

attr_profile = build_attribute_profile(work_records)

attr_stats = (
    attr_profile
    .groupby(["source", "attribute", "source_attribute_id"])
    .agg(
        count=("value", "count"),
        samples=("value", lambda x: list(pd.Series(x).dropna().astype(str).head(5)))
    )
    .reset_index()
)

schema_eval_gt = schema_gt.copy()

work_records.to_pickle(PROCESSED_DIR / "work_records.pkl")
schema_gt.to_csv(PROCESSED_DIR / "schema_ground_truth.csv", index=False)
attr_stats.to_csv(PROCESSED_DIR / "attribute_stats.csv", index=False)
pd.Series(MEDIATED_SCHEMA, name="mediated_attribute").to_csv(PROCESSED_DIR / "mediated_schema.csv", index=False)

print("Mediated schema:", MEDIATED_SCHEMA)
print("Schema GT:")
display(schema_gt)

print("Attribute stats:")
display(attr_stats)

def count_gold_pairs(records_df):
    total = 0
    rid_to_source = dict(zip(records_df["record_id"], records_df["source"]))

    for _, g in records_df.groupby("entity_id"):
        ids = sorted(g["record_id"].tolist())

        for a, b in itertools.combinations(ids, 2):
            if rid_to_source[a] != rid_to_source[b]:
                total += 1

    return total

def count_conflicts(records_df, mediated_schema, source_schemas):
    conflicts = 0

    for entity_id, group in records_df.groupby("entity_id"):
        for mediated_attr in mediated_schema:
            values = []

            for _, row in group.iterrows():
                source = row["source"]
                source_attr = source_schemas[source][mediated_attr]
                val = row["attrs"].get(source_attr, "")
                val = str(val).strip().lower()

                if val:
                    values.append(val)

            if len(set(values)) > 1:
                conflicts += 1

    return conflicts

n_sources = work_records["source"].nunique()
n_records = len(work_records)
n_entities = work_records["entity_id"].nunique()
n_positive_pairs = count_gold_pairs(work_records)
n_conflicts = count_conflicts(work_records, MEDIATED_SCHEMA, SOURCE_SCHEMAS)

print("Dataset requirement check")
print("Sources:", n_sources)
print("Records:", n_records)
print("Integrated entities:", n_entities)
print("Known positive matching pairs:", n_positive_pairs)
print("Conflicting attribute values:", n_conflicts)
print("Mediated attributes:", len(MEDIATED_SCHEMA))

if n_sources < 3:
    print("WARNING: < 3 sources")
if n_records < 1000:
    print("WARNING: < 1000 records")
if n_entities < 200:
    print("WARNING: < 200 entities")
if n_positive_pairs < 300:
    print("WARNING: < 300 positive pairs")
if n_conflicts < 100:
    print("WARNING: < 100 conflicts")
if len(MEDIATED_SCHEMA) < 5:
    print("WARNING: < 5 mediated attributes")

def normalize_text(x):
    if x is None or (isinstance(x, float) and pd.isna(x)):
        return ""
    x = str(x).lower()
    x = re.sub(r"\s+", " ", x)
    x = x.strip()
    return x

def normalize_key(x):
    x = normalize_text(x)
    x = x.replace("_", " ")
    x = x.replace("-", " ")
    x = re.sub(r"[^a-z0-9 ]+", " ", x)
    x = re.sub(r"\s+", " ", x).strip()
    return x

def normalize_value(x):
    x = normalize_text(x)
    x = re.sub(r"\s+", " ", x).strip()
    return x

def tokenize(x):
    return [t for t in normalize_key(x).split() if t]

def first_meaningful_token(text):
    stop = {"the", "a", "an", "and", "or", "for", "with", "monitor", "lcd", "led", "full", "hd"}
    for t in tokenize(text):
        if len(t) > 2 and t not in stop:
            return t
    return ""

def extract_number(x):
    x = normalize_text(x)
    m = re.search(r"\d+(?:\.\d+)?", x)
    if m:
        try:
            return float(m.group(0))
        except Exception:
            return None
    return None

def sim_text(a, b):
    a = normalize_text(a)
    b = normalize_text(b)
    if not a or not b:
        return 0.0
    return fuzz.token_set_ratio(a, b) / 100.0

def exact_or_sim(a, b):
    a = normalize_text(a)
    b = normalize_text(b)
    if not a or not b:
        return 0.0
    if a == b:
        return 1.0
    return sim_text(a, b)

def baseline_schema_align(attr_stats, mediated_schema, threshold=62):
    target_norm = {t: normalize_key(t) for t in mediated_schema}
    rows = []

    for _, r in attr_stats.iterrows():
        source_attr_id = r["source_attribute_id"]
        attr_name = r["attribute"]
        attr_norm = normalize_key(attr_name)

        best_t = None
        best_score = -1

        for t, t_norm in target_norm.items():
            score = fuzz.token_set_ratio(attr_norm, t_norm)

            if "brand" in attr_norm and "brand" in t_norm:
                score += 15
            if "manufacturer" in attr_norm and "brand" in t_norm:
                score += 12
            if "model" in attr_norm and "model" in t_norm:
                score += 15
            if "screen" in attr_norm and "screen" in t_norm:
                score += 10
            if "resolution" in attr_norm and "resolution" in t_norm:
                score += 10
            if "refresh" in attr_norm and "refresh" in t_norm:
                score += 10
            if "response" in attr_norm and "response" in t_norm:
                score += 10

            score = min(score, 100)
            if score > best_score:
                best_score = score
                best_t = t

        pred = best_t if best_score >= threshold else "ABSTAIN"
        rows.append({
            "source_attribute_id": source_attr_id,
            "source": r["source"],
            "attribute": attr_name,
            "predicted_target": pred,
            "confidence": round(best_score / 100, 4)
        })

    return pd.DataFrame(rows)

schema_baseline = baseline_schema_align(attr_stats, MEDIATED_SCHEMA)
schema_baseline.to_csv(RESULTS_DIR / "schema_alignment_baseline.csv", index=False)
schema_baseline.head()

def evaluate_schema_alignment(pred_df, gt_df, label="baseline"):
    merged = gt_df.merge(
        pred_df[["source_attribute_id", "predicted_target"]],
        on="source_attribute_id",
        how="left"
    )
    merged["predicted_target"] = merged["predicted_target"].fillna("ABSTAIN")
    merged["correct"] = merged["predicted_target"] == merged["target_attribute_name"]

    accuracy = merged["correct"].mean() if len(merged) else 0.0

    y_true_pairs = set(zip(merged["source_attribute_id"], merged["target_attribute_name"]))
    y_pred_pairs = set(
        zip(
            merged.loc[merged["predicted_target"] != "ABSTAIN", "source_attribute_id"],
            merged.loc[merged["predicted_target"] != "ABSTAIN", "predicted_target"]
        )
    )

    tp = len(y_true_pairs & y_pred_pairs)
    fp = len(y_pred_pairs - y_true_pairs)
    fn = len(y_true_pairs - y_pred_pairs)

    precision = tp / (tp + fp) if (tp + fp) else 0.0
    recall = tp / (tp + fn) if (tp + fn) else 0.0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) else 0.0

    return {
        "component": "schema_alignment",
        "pipeline": label,
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "n_eval": len(merged),
        "tp": tp,
        "fp": fp,
        "fn": fn
    }

schema_baseline_metrics = evaluate_schema_alignment(schema_baseline, schema_eval_gt, "baseline")
schema_baseline_metrics

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True
)

print("Loading model:", MODEL_ID)

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, trust_remote_code=True)

model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True
)

model.eval()
print("Model loaded.")

LLM_LOGS = []

@torch.inference_mode()
def generate_llm(prompt, max_new_tokens=512):
    messages = [{"role": "user", "content": prompt}]
    inputs = tokenizer.apply_chat_template(
        messages,
        add_generation_prompt=True,
        tokenize=True,
        return_tensors="pt",
        return_dict=True
    ).to(model.device)

    outputs = model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=False,
        temperature=0.0,
        pad_token_id=tokenizer.eos_token_id
    )

    generated = outputs[0][inputs["input_ids"].shape[-1]:]
    text = tokenizer.decode(generated, skip_special_tokens=True)
    return text.strip()

def extract_json(text):
    if text is None:
        return None

    text = text.strip()
    text = re.sub(r"^```json", "", text.strip(), flags=re.IGNORECASE).strip()
    text = re.sub(r"^```", "", text.strip()).strip()
    text = re.sub(r"```$", "", text.strip()).strip()

    m = re.search(r"\{.*\}", text, flags=re.DOTALL)
    if m:
        try:
            return json.loads(m.group(0))
        except Exception:
            pass

    m = re.search(r"\[.*\]", text, flags=re.DOTALL)
    if m:
        try:
            return json.loads(m.group(0))
        except Exception:
            pass

    try:
        return json.loads(text)
    except Exception:
        return None

def log_llm(stage, prompt, raw_response, parsed, success, metadata=None):
    LLM_LOGS.append({
        "stage": stage,
        "prompt": prompt,
        "raw_response": raw_response,
        "parsed": parsed,
        "success": success,
        "metadata": metadata or {}
    })

SCHEMA_ALIGNMENT_PROMPT_TEMPLATE = """
You are doing schema alignment for Big Data Integration.

Mediated schema:
{mediated_schema}

Source name:
{source_name}

Source attributes with sample values:
{attributes_block}

Task:
Map each source attribute to exactly one mediated attribute when you are confident.
If there is no good mapping, use "ABSTAIN".

Return ONLY valid JSON with this format:
{{
  "mappings": [
    {{
      "source_attribute": "original attribute name",
      "mediated_attribute": "one of the mediated schema attributes or ABSTAIN",
      "confidence": 0.0,
      "reason": "short reason"
    }}
  ]
}}

Rules:
- Do not invent mediated attributes.
- Use only attributes from the mediated schema.
- Use ABSTAIN when unsure.
- Return JSON only.
"""

RECORD_LINKAGE_PROMPT_TEMPLATE = """
You are doing entity resolution for product specifications.

Decide if Record A and Record B refer to the same real-world product.

Record A:
{record_a}

Record B:
{record_b}

Return ONLY valid JSON:
{{
  "match": true,
  "confidence": 0.0,
  "reason": "short explanation"
}}

Rules:
- match must be true or false.
- Focus on title, brand, model, screen size, resolution, and other technical details.
- Different models usually mean non-match.
- Do not hallucinate missing information.
- Return JSON only.
"""

DATA_FUSION_PROMPT_TEMPLATE = """
You are doing data fusion for product records.

Choose one canonical value for each attribute.

Mediated schema:
{mediated_schema}

Records:
{records_block}

Return ONLY compact valid JSON with exactly this format:
{{
  "fused": {{
    "title": "short selected value",
    "brand": "short selected value",
    "description": "short selected value",
    "price": "short selected value",
    "priceCurrency": "short selected value"
  }}
}}

Rules:
- Return JSON only.
- Do not include explanations.
- Do not include confidence.
- Do not invent unsupported values.
- Copy each selected value exactly from one of the provided records.
- Do not shorten, combine, translate, infer, or invent values.
- Use an empty string if no value is supported.
"""

(PROMPTS_DIR / "schema_alignment_prompt.txt").write_text(SCHEMA_ALIGNMENT_PROMPT_TEMPLATE)
(PROMPTS_DIR / "record_linkage_prompt.txt").write_text(RECORD_LINKAGE_PROMPT_TEMPLATE)
(PROMPTS_DIR / "data_fusion_prompt.txt").write_text(DATA_FUSION_PROMPT_TEMPLATE)

def build_attributes_block(source_attr_stats, max_attrs=35):
    lines = []
    source_attr_stats = source_attr_stats.sort_values("count", ascending=False).head(max_attrs)

    for _, r in source_attr_stats.iterrows():
        samples = r["samples"]
        if isinstance(samples, str):
            samples = [samples]
        samples_str = "; ".join([str(s)[:80] for s in samples[:3]])
        lines.append(f"- {r['attribute']} | count={r['count']} | samples: {samples_str}")

    return "\n".join(lines)

def llm_schema_align_for_source(source_name, source_attr_stats, mediated_schema):
    attributes_block = build_attributes_block(source_attr_stats, MAX_ATTRS_PER_SOURCE_FOR_LLM)

    prompt = SCHEMA_ALIGNMENT_PROMPT_TEMPLATE.format(
        mediated_schema=json.dumps(mediated_schema, indent=2),
        source_name=source_name,
        attributes_block=attributes_block
    )

    raw = generate_llm(prompt, max_new_tokens=768)
    parsed = extract_json(raw)

    success = isinstance(parsed, dict) and "mappings" in parsed and isinstance(parsed["mappings"], list)
    log_llm(
        stage="schema_alignment",
        prompt=prompt,
        raw_response=raw,
        parsed=parsed,
        success=success,
        metadata={"source": source_name}
    )

    rows = []
    if success:
        for m in parsed["mappings"]:
            src_attr = str(m.get("source_attribute", "")).strip()
            pred = str(m.get("mediated_attribute", "ABSTAIN")).strip()
            conf = m.get("confidence", 0.0)
            reason = str(m.get("reason", ""))

            if pred not in mediated_schema:
                pred = "ABSTAIN"

            source_attribute_id = f"{source_name}//{src_attr}"
            rows.append({
                "source": source_name,
                "attribute": src_attr,
                "source_attribute_id": source_attribute_id,
                "predicted_target": pred,
                "confidence": conf,
                "reason": reason
            })

    return pd.DataFrame(rows)

llm_schema_rows = []

for source_name, group in tqdm(attr_stats.groupby("source"), desc="LLM schema alignment by source"):
    df_source = llm_schema_align_for_source(source_name, group, MEDIATED_SCHEMA)
    if len(df_source):
        llm_schema_rows.append(df_source)

schema_llm_raw = pd.concat(llm_schema_rows, ignore_index=True) if llm_schema_rows else pd.DataFrame()

schema_llm = schema_baseline.copy()
schema_llm["reason"] = "baseline fallback"

if len(schema_llm_raw):
    llm_map = schema_llm_raw.set_index("source_attribute_id").to_dict("index")
    for idx, row in schema_llm.iterrows():
        sid = row["source_attribute_id"]
        if sid in llm_map:
            schema_llm.loc[idx, "predicted_target"] = llm_map[sid]["predicted_target"]
            schema_llm.loc[idx, "confidence"] = llm_map[sid]["confidence"]
            schema_llm.loc[idx, "reason"] = llm_map[sid].get("reason", "llm")

schema_llm.to_csv(RESULTS_DIR / "schema_alignment_llm.csv", index=False)

schema_llm_metrics = evaluate_schema_alignment(schema_llm, schema_eval_gt, "llm_assisted")
schema_llm_metrics

gold_mapping = dict(
    zip(schema_gt["source_attribute_id"], schema_gt["target_attribute_name"])
)

baseline_mapping = dict(
    zip(schema_baseline["source_attribute_id"], schema_baseline["predicted_target"])
)

llm_mapping = dict(
    zip(schema_llm["source_attribute_id"], schema_llm["predicted_target"])
)

def canonicalize_record(row, mapping, mediated_schema):
    source = row["source"]
    attrs = row["attrs"]
    out = {a: "" for a in mediated_schema}

    for k, v in attrs.items():
        sid = f"{source}//{k}"
        target = mapping.get(sid, "ABSTAIN")
        if target in mediated_schema:
            val = normalize_value(v)
            if val:
                if out[target]:
                    if val not in out[target]:
                        out[target] += " | " + val
                else:
                    out[target] = val

    raw_title = ""
    for k, v in attrs.items():
        nk = normalize_key(k)
        if "page title" in nk or nk == "title" or nk == "name" or "product name" in nk or "item title" in nk:
            raw_title = normalize_value(v)
            break

    if not raw_title:
        vals = sorted([str(v) for v in attrs.values()], key=len, reverse=True)
        raw_title = normalize_value(vals[0]) if vals else ""

    raw_brand = ""
    for k, v in attrs.items():
        nk = normalize_key(k)
        if "brand" in nk or "manufacturer" in nk or "maker" in nk:
            raw_brand = normalize_value(v)
            break

    raw_model = ""
    for k, v in attrs.items():
        nk = normalize_key(k)
        if "model" in nk or "part number" in nk or "mpn" in nk:
            raw_model = normalize_value(v)
            break

    out["__title"] = raw_title
    out["__brand"] = raw_brand
    out["__model"] = raw_model

    return out

def add_canonical_columns(df, mapping, prefix):
    rows = []
    for _, row in tqdm(df.iterrows(), total=len(df), desc=f"Canonicalizing {prefix}"):
        can = canonicalize_record(row, mapping, MEDIATED_SCHEMA)
        flat = {
            "record_id": row["record_id"],
            "spec_id": row["spec_id"],
            "entity_id": row["entity_id"],
            "source": row["source"],
        }
        for k, v in can.items():
            flat[f"{prefix}_{k}"] = v
        rows.append(flat)
    return pd.DataFrame(rows)

canon_baseline = add_canonical_columns(work_records, baseline_mapping, "base")
canon_llm = add_canonical_columns(work_records, llm_mapping, "llm")
canon_gold = add_canonical_columns(work_records, gold_mapping, "gold")

canon_baseline.to_csv(PROCESSED_DIR / "canonical_baseline.csv", index=False)
canon_llm.to_csv(PROCESSED_DIR / "canonical_llm.csv", index=False)
canon_gold.to_csv(PROCESSED_DIR / "canonical_gold.csv", index=False)

canon_baseline.head()

def record_view(canon_row, prefix):
    d = {}
    for a in MEDIATED_SCHEMA:
        d[a] = canon_row.get(f"{prefix}_{a}", "")
    d["title"] = canon_row.get(f"{prefix}___title", "")
    d["brand"] = canon_row.get(f"{prefix}___brand", "")
    d["model"] = canon_row.get(f"{prefix}___model", "")
    return d

def get_block_keys(row, prefix):
    title = row.get(f"{prefix}___title", "")
    brand = row.get(f"{prefix}___brand", "")
    model = row.get(f"{prefix}___model", "")

    keys = set()

    brand_n = normalize_key(brand)
    model_n = normalize_key(model)

    stop = {
        "the", "and", "for", "with", "from", "new",
        "black", "white", "red", "blue", "green",
        "inch", "inches", "pack", "set", "one",
        "free", "shipping", "original", "genuine",
        "brand", "official", "sale", "usb", "cable",
        "product", "compatible", "case", "cover"
    }

    toks = [
        t for t in tokenize(title)
        if len(t) > 2 and t not in stop
    ]

    if brand_n and toks:
        keys.add(f"brand_title::{brand_n[:20]}::{toks[0]}")

    if model_n:
        keys.add(f"model::{model_n[:30]}")

    for t in toks[:4]:
        keys.add(f"title_token::{t}")

    for i in range(min(len(toks) - 1, 3)):
        keys.add(f"title_bigram::{toks[i]}::{toks[i+1]}")

    if brand_n:
        for t in toks[:4]:
            keys.add(f"brand_token::{brand_n[:20]}::{t}")

    if len(toks) >= 2:
        keys.add(f"title2::{toks[0]}::{toks[1]}")

    return keys

def generate_candidate_pairs(canon_df, prefix, max_block_size=250):
    blocks = defaultdict(list)

    for _, row in canon_df.iterrows():
        rid = row["record_id"]
        for k in get_block_keys(row, prefix):
            blocks[k].append(rid)

    rid_to_source = dict(zip(canon_df["record_id"], canon_df["source"]))
    pairs = set()
    block_stats = []

    for key, ids in blocks.items():
        ids = list(set(ids))
        if len(ids) < 2:
            continue

        block_stats.append({"block_key": key, "block_size": len(ids)})

        if len(ids) > max_block_size:
            continue

        for a, b in itertools.combinations(sorted(ids), 2):
            if rid_to_source[a] == rid_to_source[b]:
                continue
            pairs.add(tuple(sorted((a, b))))

    pairs_df = pd.DataFrame(list(pairs), columns=["record_id_1", "record_id_2"])
    block_stats_df = pd.DataFrame(block_stats).sort_values("block_size", ascending=False)

    return pairs_df, block_stats_df

candidate_pairs_baseline, block_stats_baseline = generate_candidate_pairs(canon_baseline, "base")
candidate_pairs_llm, block_stats_llm = generate_candidate_pairs(canon_llm, "llm")

candidate_pairs_baseline.to_csv(RESULTS_DIR / "candidate_pairs_baseline.csv", index=False)
candidate_pairs_llm.to_csv(RESULTS_DIR / "candidate_pairs_llm.csv", index=False)
block_stats_baseline.to_csv(RESULTS_DIR / "blocking_stats_baseline.csv", index=False)
block_stats_llm.to_csv(RESULTS_DIR / "blocking_stats_llm.csv", index=False)

print("Baseline candidate pairs:", len(candidate_pairs_baseline))
print("LLM candidate pairs:", len(candidate_pairs_llm))
print("Top block sizes:")
block_stats_llm.head()

def build_gold_pairs(records_df):
    gold_pairs = set()
    rid_to_source = dict(zip(records_df["record_id"], records_df["source"]))

    for entity_id, g in records_df.groupby("entity_id"):
        ids = sorted(g["record_id"].tolist())

        if len(ids) >= 2:
            for a, b in itertools.combinations(ids, 2):
                if rid_to_source[a] != rid_to_source[b]:
                    gold_pairs.add(tuple(sorted((a, b))))

    return gold_pairs

gold_pairs = build_gold_pairs(work_records)

all_possible_cross_source = 0
sources_by_rid = dict(zip(work_records["record_id"], work_records["source"]))
all_ids = work_records["record_id"].tolist()

for a, b in itertools.combinations(all_ids, 2):
    if sources_by_rid[a] != sources_by_rid[b]:
        all_possible_cross_source += 1

print("Gold positive pairs:", len(gold_pairs))
print("All possible cross-source pairs:", all_possible_cross_source)

if len(gold_pairs) < 300:
    print("WARNING: < 300 positive pairs. Consider larger subset.")

def evaluate_linkage(linkage_df, gold_pairs, label="baseline"):
    pred_pairs = set()
    for _, r in linkage_df[linkage_df["pred_match"] == 1].iterrows():
        pred_pairs.add(tuple(sorted((r["record_id_1"], r["record_id_2"]))))

    tp = len(pred_pairs & gold_pairs)
    fp = len(pred_pairs - gold_pairs)
    fn = len(gold_pairs - pred_pairs)

    precision = tp / (tp + fp) if (tp + fp) else 0.0
    recall = tp / (tp + fn) if (tp + fn) else 0.0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) else 0.0

    return {
        "component": "record_linkage",
        "pipeline": label,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "candidate_pairs": len(linkage_df),
        "predicted_matches": len(pred_pairs),
        "gold_positive_pairs": len(gold_pairs),
        "tp": tp,
        "fp": fp,
        "fn": fn
    }

def make_record_dicts(canon_df, prefix):
    out = {}

    for _, row in canon_df.iterrows():
        d = {
            "record_id": row["record_id"],
            "spec_id": row["spec_id"],
            "entity_id": row["entity_id"],
            "source": row["source"],
        }

        for a in MEDIATED_SCHEMA:
            v = row.get(f"{prefix}_{a}", "")
            if pd.isna(v):
                v = ""
            d[a] = v

        for aux in ["title", "brand", "model"]:
            v = row.get(f"{prefix}___{aux}", "")
            if not pd.isna(v) and str(v).strip():
                d[aux] = v

        out[row["record_id"]] = d

    return out


def pair_features(a, b):
    title_sim = sim_text(a.get("title", ""), b.get("title", ""))
    brand_sim = exact_or_sim(a.get("brand", ""), b.get("brand", ""))
    model_sim = exact_or_sim(a.get("model", ""), b.get("model", ""))

    mediated_sims = []
    for attr in MEDIATED_SCHEMA:
        va = a.get(attr, "")
        vb = b.get(attr, "")
        if va and vb:
            mediated_sims.append(sim_text(va, vb))

    attr_sim = float(np.mean(mediated_sims)) if mediated_sims else 0.0

    score = (
        0.45 * title_sim +
        0.20 * brand_sim +
        0.20 * model_sim +
        0.15 * attr_sim
    )

    return {
        "title_sim": title_sim,
        "brand_sim": brand_sim,
        "model_sim": model_sim,
        "attr_sim": attr_sim,
        "score": score
    }


def baseline_pair_matching(candidate_pairs, record_dict):
    rows = []

    for _, r in tqdm(candidate_pairs.iterrows(), total=len(candidate_pairs), desc="Baseline pair matching"):
        r1, r2 = r["record_id_1"], r["record_id_2"]

        a = record_dict[r1]
        b = record_dict[r2]

        feats = pair_features(a, b)
        pred = feats["score"] >= MATCH_THRESHOLD

        rows.append({
            "record_id_1": r1,
            "record_id_2": r2,
            **feats,
            "pred_match": int(pred)
        })

    return pd.DataFrame(rows)

base_records = make_record_dicts(canon_baseline, "base")
llm_records = make_record_dicts(canon_llm, "llm")

linkage_baseline = baseline_pair_matching(candidate_pairs_baseline, base_records)
linkage_baseline.to_csv(RESULTS_DIR / "record_linkage_baseline.csv", index=False)

linkage_baseline_metrics = evaluate_linkage(linkage_baseline, gold_pairs, "baseline")
linkage_baseline_metrics

def compact_record_for_prompt(record):
    keep = list(dict.fromkeys(["title", "brand", "model"] + MEDIATED_SCHEMA))
    parts = []

    for k in keep:
        v = record.get(k, "")
        if v:
            parts.append(f"{k}: {str(v)[:250]}")

    return "\n".join(parts)

def llm_judge_pair(record_a, record_b, metadata=None):
    prompt = RECORD_LINKAGE_PROMPT_TEMPLATE.format(
        record_a=compact_record_for_prompt(record_a),
        record_b=compact_record_for_prompt(record_b)
    )

    raw = generate_llm(prompt, max_new_tokens=240)
    parsed = extract_json(raw)

    success = isinstance(parsed, dict) and "match" in parsed
    log_llm(
        stage="record_linkage",
        prompt=prompt,
        raw_response=raw,
        parsed=parsed,
        success=success,
        metadata=metadata
    )

    if not success:
        return None

    match = parsed.get("match", False)
    confidence = parsed.get("confidence", 0.0)
    reason = parsed.get("reason", "")

    return {
        "llm_match": bool(match),
        "llm_confidence": float(confidence) if isinstance(confidence, (int, float)) else 0.0,
        "llm_reason": str(reason)
    }

linkage_llm_base_scores = baseline_pair_matching(candidate_pairs_llm, llm_records)

borderline = linkage_llm_base_scores[
    (linkage_llm_base_scores["score"] >= BORDERLINE_LOW) &
    (linkage_llm_base_scores["score"] < BORDERLINE_HIGH)
].copy()

borderline = borderline.sort_values("score", ascending=False).head(MAX_LLM_LINKAGE_CALLS)
borderline_ids = set(zip(borderline["record_id_1"], borderline["record_id_2"]))

print("Borderline pairs selected for LLM:", len(borderline_ids))

llm_decisions = {}

for _, r in tqdm(borderline.iterrows(), total=len(borderline), desc="LLM record linkage"):
    rid1, rid2 = r["record_id_1"], r["record_id_2"]
    result = llm_judge_pair(
        llm_records[rid1],
        llm_records[rid2],
        metadata={"record_id_1": rid1, "record_id_2": rid2, "score": r["score"]}
    )
    if result is not None:
        llm_decisions[(rid1, rid2)] = result

linkage_llm = linkage_llm_base_scores.copy()
linkage_llm["used_llm"] = 0
linkage_llm["llm_confidence"] = np.nan
linkage_llm["llm_reason"] = ""

for idx, r in linkage_llm.iterrows():
    key = (r["record_id_1"], r["record_id_2"])
    if key in llm_decisions:
        d = llm_decisions[key]
        linkage_llm.loc[idx, "pred_match"] = int(d["llm_match"])
        linkage_llm.loc[idx, "used_llm"] = 1
        linkage_llm.loc[idx, "llm_confidence"] = d["llm_confidence"]
        linkage_llm.loc[idx, "llm_reason"] = d["llm_reason"]

linkage_llm.to_csv(RESULTS_DIR / "record_linkage_llm.csv", index=False)

linkage_llm_metrics = evaluate_linkage(linkage_llm, gold_pairs, "llm_assisted")
linkage_llm_metrics

class UnionFind:
    def __init__(self, items):
        self.parent = {x: x for x in items}
        self.rank = {x: 0 for x in items}

    def find(self, x):
        if self.parent[x] != x:
            self.parent[x] = self.find(self.parent[x])
        return self.parent[x]

    def union(self, a, b):
        ra, rb = self.find(a), self.find(b)
        if ra == rb:
            return
        if self.rank[ra] < self.rank[rb]:
            self.parent[ra] = rb
        elif self.rank[ra] > self.rank[rb]:
            self.parent[rb] = ra
        else:
            self.parent[rb] = ra
            self.rank[ra] += 1

def build_clusters(records_df, linkage_df):
    uf = UnionFind(records_df["record_id"].tolist())

    for _, r in linkage_df[linkage_df["pred_match"] == 1].iterrows():
        uf.union(r["record_id_1"], r["record_id_2"])

    root_to_cluster = {}
    rows = []
    for rid in records_df["record_id"]:
        root = uf.find(rid)
        if root not in root_to_cluster:
            root_to_cluster[root] = f"c{len(root_to_cluster)}"
        rows.append({
            "record_id": rid,
            "cluster_id": root_to_cluster[root]
        })

    return pd.DataFrame(rows)

clusters_baseline = build_clusters(work_records, linkage_baseline)
clusters_llm = build_clusters(work_records, linkage_llm)

clusters_baseline.to_csv(RESULTS_DIR / "clusters_baseline.csv", index=False)
clusters_llm.to_csv(RESULTS_DIR / "clusters_llm.csv", index=False)

print("Baseline clusters:", clusters_baseline["cluster_id"].nunique())
print("LLM clusters:", clusters_llm["cluster_id"].nunique())

def choose_majority_value(values):
    values = [normalize_value(v) for v in values if normalize_value(v)]
    if not values:
        return ""

    counts = Counter(values)
    max_count = max(counts.values())
    candidates = [v for v, c in counts.items() if c == max_count]

    candidates = sorted(candidates, key=lambda x: (len(x), x), reverse=True)
    return candidates[0]

def build_gold_canonical_by_entity(canon_gold_df):
    rows = []
    for entity_id, g in canon_gold_df.groupby("entity_id"):
        row = {"entity_id": entity_id}
        for attr in MEDIATED_SCHEMA:
            vals = g[f"gold_{attr}"].dropna().astype(str).tolist()
            vals = [v for v in vals if normalize_value(v)]
            row[attr] = choose_majority_value(vals)

            unique_vals = set(normalize_value(v) for v in vals if normalize_value(v))
            row[f"{attr}__n_values"] = len(unique_vals)
            row[f"{attr}__has_conflict"] = int(len(unique_vals) > 1)
        rows.append(row)
    return pd.DataFrame(rows)

fusion_gold = build_gold_canonical_by_entity(canon_gold)
fusion_gold.to_csv(PROCESSED_DIR / "fusion_silver_ground_truth.csv", index=False)

conflict_count = int(fusion_gold[[f"{a}__has_conflict" for a in MEDIATED_SCHEMA]].sum().sum())
print("Fusion silver truth entities:", fusion_gold.shape)
print("Conflicting entity-attribute cases:", conflict_count)

if conflict_count < 100:
    print("WARNING: < 100 conflicts detected in selected mediated schema. Consider adding more attributes.")

def fuse_cluster(records_ids, canon_df, prefix):
    sub = canon_df[canon_df["record_id"].isin(records_ids)]
    fused = {}
    for attr in MEDIATED_SCHEMA:
        vals = sub[f"{prefix}_{attr}"].dropna().astype(str).tolist()
        vals = [v for v in vals if normalize_value(v)]
        fused[attr] = choose_majority_value(vals)
    return fused

def build_fused_dataset(canon_df, clusters_df, prefix, pipeline_name):
    rows = []
    cluster_map = clusters_df.groupby("cluster_id")["record_id"].apply(list).to_dict()

    for cid, rids in cluster_map.items():
        fused = fuse_cluster(rids, canon_df, prefix)
        row = {
            "cluster_id": cid,
            "pipeline": pipeline_name,
            "n_records": len(rids),
            "record_ids": json.dumps(rids)
        }
        row.update(fused)
        rows.append(row)

    return pd.DataFrame(rows)

fused_baseline = build_fused_dataset(canon_baseline, clusters_baseline, "base", "baseline")
fused_llm_initial = build_fused_dataset(canon_llm, clusters_llm, "llm", "llm_assisted_initial")

fused_baseline.to_csv(RESULTS_DIR / "integrated_dataset_baseline.csv", index=False)
fused_llm_initial.to_csv(RESULTS_DIR / "integrated_dataset_llm_initial.csv", index=False)

fused_baseline.head()

def records_block_for_fusion(record_ids, canon_df, prefix, max_records=3):
    sub = canon_df[canon_df["record_id"].isin(record_ids)].head(max_records)
    blocks = []
    for _, row in sub.iterrows():
        d = {
            "record_id": row["record_id"],
            "source": row["source"]
        }
        for a in MEDIATED_SCHEMA:
            val = row.get(f"{prefix}_{a}", "")
            if val:
                d[a] = val
        title = row.get(f"{prefix}___title", "")
        brand = row.get(f"{prefix}___brand", "")
        model_v = row.get(f"{prefix}___model", "")
        if title:
            d["raw_title"] = title
        if brand:
            d["raw_brand"] = brand
        if model_v:
            d["raw_model"] = model_v
        blocks.append(d)
    return json.dumps(blocks, indent=2)

def has_cluster_conflict(record_ids, canon_df, prefix):
    sub = canon_df[canon_df["record_id"].isin(record_ids)]
    for attr in MEDIATED_SCHEMA:
        vals = set(normalize_value(v) for v in sub[f"{prefix}_{attr}"].dropna().astype(str) if normalize_value(v))
        if len(vals) > 1:
            return True
    return False

def llm_fuse_cluster(record_ids, canon_df, prefix, metadata=None):
    records_block = records_block_for_fusion(
        record_ids,
        canon_df,
        prefix
    )

    prompt = DATA_FUSION_PROMPT_TEMPLATE.format(
        mediated_schema=json.dumps(MEDIATED_SCHEMA, indent=2),
        records_block=records_block
    )

    raw = generate_llm(prompt, max_new_tokens=384)
    parsed = extract_json(raw)

    valid_json = (
        isinstance(parsed, dict)
        and isinstance(parsed.get("fused"), dict)
    )

    fallback = fuse_cluster(
        record_ids,
        canon_df,
        prefix
    )

    if not valid_json:
        log_llm(
            stage="data_fusion",
            prompt=prompt,
            raw_response=raw,
            parsed=parsed,
            success=False,
            metadata={
                **(metadata or {}),
                "fallback": "invalid_json"
            }
        )

        return fallback, False

    sub = canon_df[
        canon_df["record_id"].isin(record_ids)
    ]

    fused = fallback.copy()
    accepted_attributes = []
    rejected_attributes = []

    for attr in MEDIATED_SCHEMA:
        val_obj = parsed["fused"].get(attr, "")

        if isinstance(val_obj, dict):
            candidate = normalize_value(
                val_obj.get("value", "")
            )
        else:
            candidate = normalize_value(val_obj)

        supported_values = {
            normalize_value(value)
            for value in sub[
                f"{prefix}_{attr}"
            ].dropna().astype(str)
            if normalize_value(value)
        }

        if candidate and candidate in supported_values:
            fused[attr] = candidate
            accepted_attributes.append(attr)

        elif candidate:
            rejected_attributes.append(attr)

    log_llm(
        stage="data_fusion",
        prompt=prompt,
        raw_response=raw,
        parsed=parsed,
        success=(
            bool(accepted_attributes)
            and not rejected_attributes
        ),
        metadata={
            **(metadata or {}),
            "accepted_attributes": accepted_attributes,
            "unsupported_attributes": rejected_attributes,
            "fallback": "majority_voting"
        }
    )

    return fused, bool(accepted_attributes)


fused_llm = fused_llm_initial.copy()
fused_llm["used_llm_fusion"] = 0

cluster_to_records = (
    clusters_llm
    .groupby("cluster_id")["record_id"]
    .apply(list)
    .to_dict()
)

conflict_clusters = []

for cid, rids in cluster_to_records.items():
    if (
        len(rids) >= 2
        and has_cluster_conflict(
            rids,
            canon_llm,
            "llm"
        )
    ):
        conflict_clusters.append((cid, rids))

conflict_clusters = conflict_clusters[
    :MAX_LLM_FUSION_CALLS
]

print(
    "Conflict clusters selected for LLM fusion:",
    len(conflict_clusters)
)

for cid, rids in tqdm(
    conflict_clusters,
    desc="LLM data fusion"
):
    result, used_valid_llm_value = llm_fuse_cluster(
        rids,
        canon_llm,
        "llm",
        metadata={
            "cluster_id": cid,
            "record_ids": rids
        }
    )

    idxs = fused_llm.index[
        fused_llm["cluster_id"] == cid
    ].tolist()

    if not idxs:
        continue

    idx = idxs[0]

    for attr, val in result.items():
        if attr in MEDIATED_SCHEMA and val:
            fused_llm.loc[idx, attr] = val

    fused_llm.loc[
        idx,
        "used_llm_fusion"
    ] = int(used_valid_llm_value)

fused_llm["pipeline"] = "llm_assisted"

fused_llm.to_csv(
    RESULTS_DIR / "integrated_dataset_llm.csv",
    index=False
)

fused_llm.head()

def map_pred_clusters_to_gold(clusters_df, records_df):
    tmp = clusters_df.merge(records_df[["record_id", "entity_id"]], on="record_id", how="left")
    mapping = {}

    for cid, g in tmp.groupby("cluster_id"):
        if g["entity_id"].isna().all():
            continue
        majority_entity = g["entity_id"].value_counts().idxmax()
        mapping[cid] = majority_entity

    return mapping

def evaluate_fusion(fused_df, clusters_df, fusion_gold_df, records_df, label):
    cluster_to_entity = map_pred_clusters_to_gold(clusters_df, records_df)
    gold_by_entity = fusion_gold_df.set_index("entity_id").to_dict("index")

    rows = []
    total = 0
    correct = 0

    for _, row in fused_df.iterrows():
        cid = row["cluster_id"]
        entity = cluster_to_entity.get(cid)
        if entity not in gold_by_entity:
            continue

        gold = gold_by_entity[entity]
        for attr in MEDIATED_SCHEMA:
            gold_val = normalize_value(gold.get(attr, ""))
            pred_val = normalize_value(row.get(attr, ""))

            if not gold_val:
                continue

            is_correct = pred_val == gold_val
            total += 1
            correct += int(is_correct)
            rows.append({
                "pipeline": label,
                "cluster_id": cid,
                "entity_id": entity,
                "attribute": attr,
                "predicted_value": pred_val,
                "gold_value": gold_val,
                "correct": int(is_correct)
            })

    acc = correct / total if total else 0.0
    return {
        "component": "data_fusion",
        "pipeline": label,
        "accuracy": acc,
        "n_eval_values": total,
        "correct_values": correct
    }, pd.DataFrame(rows)

fusion_baseline_metrics, fusion_baseline_eval = evaluate_fusion(
    fused_baseline, clusters_baseline, fusion_gold, work_records, "baseline"
)

fusion_llm_metrics, fusion_llm_eval = evaluate_fusion(
    fused_llm, clusters_llm, fusion_gold, work_records, "llm_assisted"
)

fusion_baseline_eval.to_csv(RESULTS_DIR / "fusion_eval_baseline.csv", index=False)
fusion_llm_eval.to_csv(RESULTS_DIR / "fusion_eval_llm.csv", index=False)

fusion_baseline_metrics, fusion_llm_metrics

def build_linkage_error_examples(linkage_df, record_dict, gold_pairs, label, max_examples=20):
    rows = []

    for _, r in linkage_df.iterrows():
        pair = tuple(sorted((r["record_id_1"], r["record_id_2"])))
        pred = int(r["pred_match"])
        gold = int(pair in gold_pairs)

        if pred != gold:
            a = record_dict[r["record_id_1"]]
            b = record_dict[r["record_id_2"]]
            rows.append({
                "pipeline": label,
                "error_type": "false_positive" if pred == 1 else "false_negative",
                "record_id_1": r["record_id_1"],
                "record_id_2": r["record_id_2"],
                "score": r.get("score", None),
                "pred_match": pred,
                "gold_match": gold,
                "record_1": json.dumps(a, ensure_ascii=False),
                "record_2": json.dumps(b, ensure_ascii=False)
            })

    return pd.DataFrame(rows).head(max_examples)

baseline_linkage_errors = build_linkage_error_examples(linkage_baseline, base_records, gold_pairs, "baseline")
llm_linkage_errors = build_linkage_error_examples(linkage_llm, llm_records, gold_pairs, "llm_assisted")

baseline_linkage_errors.to_csv(RESULTS_DIR / "error_examples_linkage_baseline.csv", index=False)
llm_linkage_errors.to_csv(RESULTS_DIR / "error_examples_linkage_llm.csv", index=False)

def fusion_error_examples(fusion_eval_df, label, max_examples=20):
    return fusion_eval_df[fusion_eval_df["correct"] == 0].head(max_examples).assign(pipeline=label)

fusion_errors_baseline = fusion_error_examples(fusion_baseline_eval, "baseline")
fusion_errors_llm = fusion_error_examples(fusion_llm_eval, "llm_assisted")

fusion_errors_baseline.to_csv(RESULTS_DIR / "error_examples_fusion_baseline.csv", index=False)
fusion_errors_llm.to_csv(RESULTS_DIR / "error_examples_fusion_llm.csv", index=False)

baseline_linkage_errors.head()

logs_path = RESULTS_DIR / "llm_logs.jsonl"
with open(logs_path, "w", encoding="utf-8") as f:
    for item in LLM_LOGS:
        f.write(json.dumps(item, ensure_ascii=False) + "\n")

print("Saved LLM logs:", logs_path)
print("Total LLM calls:", len(LLM_LOGS))
print(pd.Series([x["stage"] for x in LLM_LOGS]).value_counts())

metrics_rows = []

metrics_rows.append(schema_baseline_metrics)
metrics_rows.append(schema_llm_metrics)
metrics_rows.append(linkage_baseline_metrics)
metrics_rows.append(linkage_llm_metrics)
metrics_rows.append(fusion_baseline_metrics)
metrics_rows.append(fusion_llm_metrics)

metrics_rows.append({
    "component": "blocking",
    "pipeline": "baseline",
    "candidate_pairs": len(candidate_pairs_baseline),
    "all_possible_cross_source_pairs": all_possible_cross_source,
    "reduction_ratio": 1 - (len(candidate_pairs_baseline) / all_possible_cross_source if all_possible_cross_source else 0)
})

metrics_rows.append({
    "component": "blocking",
    "pipeline": "llm_assisted",
    "candidate_pairs": len(candidate_pairs_llm),
    "all_possible_cross_source_pairs": all_possible_cross_source,
    "reduction_ratio": 1 - (len(candidate_pairs_llm) / all_possible_cross_source if all_possible_cross_source else 0)
})

metrics_rows.append({
    "component": "llm_usage",
    "pipeline": "llm_assisted",
    "total_llm_calls": len(LLM_LOGS),
    "schema_alignment_calls": sum(1 for x in LLM_LOGS if x["stage"] == "schema_alignment"),
    "record_linkage_calls": sum(1 for x in LLM_LOGS if x["stage"] == "record_linkage"),
    "data_fusion_calls": sum(1 for x in LLM_LOGS if x["stage"] == "data_fusion")
})

metrics_summary = pd.DataFrame(metrics_rows)
metrics_summary.to_csv(RESULTS_DIR / "metrics_summary.csv", index=False)

metrics_summary